spring:
  datasource:
    url: jdbc:h2:mem:zpsm;INIT=CREATE SCHEMA IF NOT EXISTS zpsm_projekt
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

jwt:
  secret: "enBzbV9wcm9qZWt0X3JwZ19zZXNzaW9uX2Fzc2lzc3RhbnRfMmsyMw=="
  accessTokenExpirationAfterHours: 8
  refreshTokenExpirationAfterHours: 24
